package flag

const (
	Async                = "async"
	Bucket               = "bucket"
	Compression          = "compression"
	Collection           = "collection"
	Cursor               = "cursor"
	Dataset              = "dataset"
	Description          = "description"
	Docs                 = "docs"
	Email                = "email"
	File                 = "file"
	Force                = "force"
	IngestTransformation = "ingest-transformation"
	Integration          = "integration"
	Offset               = "offset"
	Pattern              = "pattern"
	Region               = "region"
	Retention            = "retention"
	Role                 = "role"
	RoleARN              = "role-arn"
	Size                 = "size"
	SQL                  = "sql"
	State                = "state"
	Tag                  = "tag"
	Tags                 = "tags"
	Validate             = "validate"
	VI                   = "vi"
	Version              = "version"
	Versions             = "versions"
	Wait                 = "wait"
	Workspace            = "workspace"
	WorkspaceShort       = "W"
)
