repos:
-   repo: local
    hooks:
      - id: gofmt
        name: "go fmt"
        entry: gofmt
        language: system
        'types_or': [go]
        args: ["-w", "-s"]
        require_serial: false
        additional_dependencies: []
        minimum_pre_commit_version: 2.9.2
      - id: govet
        name: "go vet"
        entry: go
        language: system
        'types_or': [go]
        args: ["vet", "./..."]
        require_serial: false
        pass_filenames: false
        additional_dependencies: []
        minimum_pre_commit_version: 2.9.2
      - id: gotest
        name: "go test"
        entry: go
        language: system
        'types_or': [go]
        args: ["test", "-v", "./..."]
        require_serial: false
        pass_filenames: false
        additional_dependencies: []
        minimum_pre_commit_version: 2.9.2
